### ISSUE TITLE
JSON-RPC Client WebSockets / CLI Chain Notify

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1119]
**Task summary**

The forest CLI rpc-client needs to be able to make RPC calls using WebSockets.

**Specification reference**

ACs:
- [x] Supports traditional transactional RPC calls over WS (if HTTP is somehow not accessible for some reason)
- [x] Supports streaming responses from ChainNotify
- [ ] `forest chain notify` prints block height, block count, and an array of miner IDs

Example output of a `chain notify` command consists of a stream of messages printed to stdout:

`970846 - 9 blocks mined by ["f02303", "f020331", "f01036920", "f0152337", "f0130727", "f0102358", "f0723641", "f0160870", "f0816168"]`
`970847 - 7 blocks mined by ["f089358", "f0427688", "f0127595", "f09652", "f0122533", "f0807383", "f010424"]`

To access ChainNotify by hand:

`cargo install manx`
`forest` (after make install, and in another terminal)
`manx ws://127.0.0.1:1234/rpc/v0`
`{"jsonrpc": "2.0", "method":"Filecoin.ChainNotify", "params": [], "id": 0}`

**Other information and links**

https://github.com/ChainSafe/forest/pull/1100#pullrequestreview-671564178
https://github.com/ChainSafe/forest/pull/1100#issuecomment-850631576
https://github.com/ChainSafe/forest/pull/1100#issuecomment-850633068

**Comment by dtynn** [comment]
hi, you can  to give [jsonrpc-core-client](https://crates.io/crates/jsonrpc-core-client) a shot?
i wrote a small program, and it works well with a lotus node, for the simple request-response methods

**Comment by cryptoquick** [comment]
@dtynn No, we built our own, based on `jsonrpc_v2`:
https://github.com/ChainSafe/forest/blob/main/node/rpc-client/src/lib.rs

We needed more functionality than the Parity client exposed at the time, and it wasn't too hard to implement.
