### ISSUE TITLE
OpenRPC Schema Validation

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1123]
**Task summary**

We need to validate our RPC API against the Lotus OpenRPC schema.

**Specification reference**

This will be implemented in a build script.

- [x] Parse Lotus OpenRPC
  - [x] Method name
  - [x] Params
  - [x] Result
- [x] Parse a `syn` syntax tree of the `rpc-api` crate
- [x] Print a report comparing the Forest API to Lotus's

**Other information and links**

An OpenRPC schema can be generated in the latest Lotus repo using the following commands:
- `make docsgen`
- `./docgen-openrpc "api/api_full.go" "FullNode" "api" "./api" > build/openrpc/full.json`

Currently the Lotus makefile gzips OpenRPC schemas by default, and I'm not sure how to extract the archive, it looks like an empty folder, but not an empty archive. Regardless, the last command works.

Generated OpenRPC JSON wil be committed to the repo since there's no easy way to get the definitions otherwise.
