### ISSUE TITLE
Fix `wallet verify`

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1165]
**Task summary**

After #1128 is merged, all the wallet commands work, except for `wallet verify`. There's enough value in that PR, I wouldn't want it to be held up by this, so I'd like to track this separately. PRs don't necessarily have to be perfect if they don't break existing behavior, and their flaws are tracked. It's more important to keep code from growing stale.

**Specification reference**

- Currently `wallet verify` fails with `JSON RPC Error: Code: 0 Message: Decoding for address failed: non-zero trailing bits at 1`
- [ ] AC: `FULLNODE_API_INFO="<admin JWT>:/ip4/127.0.0.1/tcp/1234/http" forest wallet sign -m 'f33f' -a <wallet address>` results in similar behavior to how lotus works.

**Other information and links**

![Screenshot from 2021-06-14 13-05-59](https://user-images.githubusercontent.com/285690/121953201-80485580-cd1a-11eb-94f2-0578688e37b3.png)

This is likely not an issue with the Forest CLI, but instead, something behind the RPC server.

**Comment by cryptoquick** [comment]
Compare this to the lotus CLI output:
![Screenshot from 2021-06-15 12-47-07](https://user-images.githubusercontent.com/285690/122106990-d202e580-cdd7-11eb-83ff-874a59ba9321.png)

**Comment by cryptoquick** [comment]
Also, here's the lotus CLI when using the lotus server
![Screenshot from 2021-06-15 12-59-07](https://user-images.githubusercontent.com/285690/122110295-9bc76500-cddb-11eb-9586-696d0c563e1c.png)

I couldn't test with forest, since `forest wallet new` fails when using my lotus server. I recommend you get lotus building, @connormullett , since you'll need to have a lotus build for 3 of the 4 different usage combinations:
- [x] lotus CLI and lotus daemon
- [x] lotus CLI and forest daemon
- [x] forest CLI and lotus daemon
- [ ] forest CLI and forest daemon

**Comment by connormullett** [comment]
> I couldn't test with forest, since `forest wallet new` fails when using my lotus server. I recommend you get lotus building, @connormullett , since you'll need to have a lotus build for 3 of the 4 different usage combinations:

Its built and installed on my desktop at home, lotus isn't playing nice with apple silicon. Working on it. Thanks for the screenshots tho
