### ISSUE TITLE
Open source TODO

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/forest#117]
As we approach open sourcing the codebase we need to clean up the following todo list:
- [x] Cleanup inline documentation
- [x] Clean up CI
- [x] Auto-generate cargo doc & push to githubdocs => chainsafe.github.io/ferret
- [ ] Setup Gitbook => ferret.chainsafe.io (Maybe)
- [ ] Setup task management to be open-source friendly (e.g. tagging small tasks as Good First Issue)
- [x] Add proper license and license headers
