### ISSUE TITLE
[Tracking] Release 0.1.0-alpha

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#1231]
Meta tracking ticket towards a first alpha release for `forest`.

Non-technical issues
- [ ] Use `rustc` `stable` everywhere, do not pin outdated rust versions, ref #1228 
- [ ] Enable CI build-and-test matrix: `rustc` `stable` on `linux`, `rustc` `nightly` on `linux`, `rustc` `stable` on `macos`, `rustc` `nightly` on `macos`
- [x] Enable CI security checks, linter, docs
- [ ] Ensure all pipelines pass (green!)
- [ ] Implement client version reporting, including release track and git short hash, ref #1229 
- [ ] Implement an alpha release track (Cargo build feature)
- [ ] Fix copyright headers, ref #1230
- [ ] Publish documentation
- [ ] Initialize Changelog, known issues
- [ ] Create release pipeline on a tag to provide binaries (TBD?)

Technical issues
- [ ] #1182
- [ ] #1192
- _TBD, feel free to add release blockers_

**Comment by q9f** [comment]
🎉 

https://github.com/ChainSafe/forest/releases/tag/v0.1.0
