### ISSUE TITLE
implement payment channel manager

### ISSUE THREAD

**Issue by noot** [ChainSafe/forest#1400]
**Issue summary**

**Task summary**

as part of retrieval markets, the miner and the retriever need to be able to open a payment channel between them, so the retriever can incrementally pay the miner for some portion of the data.

within filecoin, there is already a payment channel actor that can be called into for this, however a manager around the actor is needed to allow users to easily open a channel, send payments on it, and close it. 

**Acceptance Criteria**

- [ ] two users are able to open a payment channel between each other
- [ ] one user is able to incrementally pay the other over this channel
- [ ] the channel is closed when it's no longer needed

**Other information and links**

see https://github.com/filecoin-project/lotus/tree/master/paychmgr for the go implementation

**Comment by LesnyRumcajs** [comment]
Stale and not in plans anytime soon.
