### ISSUE TITLE
Reduce code duplication between Forest and ref-fvm

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1448]
**Issue summary**
A lot of Forest code has been copied over to [ref-fvm](https://github.com/filecoin-project/ref-fvm), including some primitives like AMT or HAMT. This makes maintenance a bit of a burden because each fix in Forest should be potentially backported to ref-fvm. On top of that, between copying the code from Forest and resolving this task, some code may not have been backported - so it may not be a straightforward delete-reuse task.
**Task summary**
- [ ] Use as much code from ref-fvm as possible. Ideally, there should be no duplicate structure/function between those two repositories.
- [ ] Ensure fixes are backported.

**Acceptance Criteria**
- [ ] Code duplication between Forest and ref-fvm is gone without breaking any functionalities.

**Other information and links**
We will be able to get rid of lots of code once we remove the native backend in favour of fvm. Once https://github.com/ChainSafe/forest/pull/1403 is closed this should be governed by a `USE_FVM` env variable.

**Comment by lemmih** [comment]
Closing this issue. All code has been de-duplicated except for `legacy-amt` which is tracked by this issue: https://github.com/ChainSafe/forest/issues/1549
