### ISSUE TITLE
Nightly integration tests

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1455]
## Description
Every night (e.g. midnight UTC) we would automatically clone the latest `main` and download the latest Mainnet snapshot (approx. 50 GB) and possibly also Calibnet (approx. 5 GB). We could download the snapshots e.g. every week.

Pros:
- PR checks are as fast as now,
- Some level of confidence achieved
- Check the current state regardless of repository activity (e.g. network update)

Cons:
- A long feedback loop - in worst case scenario we would have `main` broken for over 24 hours,
- In case of several merges to master in this period - it may be harder to find the culprit
- Devs still need to run their node manually to verify that everything works.
- Dedicated VPS cost.

## Tasks to do
- [x] implement locally proper health check assertion - given a running and syncing node, we should have a metric/set of metrics that would indicate whether Forest is working correctly - for now `mainnet` only. Should most likely use what is exposed via Prometheus endpoint
- [x] migrate the above to a dedicated VPS - maybe consider `terraform`
- [x] set up cron jobs (e.g. run every day at midnight UTC but download new latest snapshot once a week)
- [ ] snapshot retention policy (e.g. keep last 2 only)
- [x] notification to Forest team Slack channel in case of failure

Optional:
- [ ] GH badge because they are shiny
