### ISSUE TITLE
Continuous Deployment of Forest client

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1459]
**Issue summary**
I imagine here that we would have a dedicated VPS on AWS that would get upgraded on successful merge to `main`. We could expose Grafana for everyone to see (if we are proud of the results) and in a way have continuous proof that everything is working fine. On possible incidents, we could send notifications.

Pros:

- Real-time view on Forest state in a real network,
- Shiny dashboards for everyone to see - it may be a tipping point for someone (probably not until we are competitive with features).
- If we would expect someone to really use Forest, it’d be best to prove that it’s continuously working (and doesn’t get e.g. OOMed after 24 hours)

Cons:

- Maintenance time, especially in the early stages.
- Dedicated VPS cost.

**Task summary**
- [x] Create a dedicated VPS on AWS running Forest on mainnet,
- [x] Implement a workflow that on a successful merge to `main`, the node on AWS is upgraded (consider using self-hosted GH runners, may facilitate this upgrade),
- [x] Slack notifications on incidents
- [ ] Grafana dashboard

**Acceptance Criteria**

- [x] On a new merge to `main`, the Forest node on AWS gets upgraded
- [x] Forest team gets notifications on failures
- [ ] Community can see the status of the node

**Other information and links**

**Comment by lemmih** [comment]
Almost done. AWS turned into Digital Ocean. Still need a public dashboard.

**Comment by LesnyRumcajs** [comment]
We have conitnuous deployment for calibnet, mainnet and butterflynet. Public dashboard will likely not come there (but it may appear somewhere else).
