### ISSUE TITLE
Pull Request integration tests

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1460]
**Issue summary**

Forest sync checks would run on every PR to `main`. We could use a self-hosted worker to reduce snapshot download time.

Pros:
- more confidence in CI, each PR would get tested on a prod-like environment which in turn would reduce manual testing time,
- No feedback in case of a network upgrade.

Cons:
- PR checks times would most likely get a lot longer. We could reduce it a bit by checking only Calibnet (~10x smaller snapshot).
- BuildJet builds cost.

**Task summary**
- [ ] Implement PR sync checks, perhaps take inspiration from nightly runs (https://github.com/ChainSafe/forest/issues/1455). The best would be to check both mainnet and calibnet, but if it significantly extends check time, we could go with the shorter one.

**Acceptance Criteria**

- [x] Calibnet / mainnet syncs are verified on each PR,
- [x] Overall PR check time is not significantly increased

**Other information and links**

**Comment by lemmih** [comment]
We now have calibnet sync checks in the CI and mainnet sync checks as an external service. Can I close this issue, Hubert? If not, let's rewrite the acceptance criteria.

**Comment by LesnyRumcajs** [comment]
Yeah, sounds good. I'd even say that in the future we should have only a local devnet in GH PR so it's better isolated (that is to say, we would have a true integration test and not an e2e).
