### ISSUE TITLE
Coverage check on PR

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1465]
**Issue summary**
Introduce a coverage check for PRs. Coverage check should fail if the metric drops. It should pass if it stays the same (to not harass innocent people trying to fix a typo in README).

**Task summary**
We already have a coverage report, now we need to somehow check if the reported coverage is not lower than the one from before the changes. Maybe it can be extracted from `codecov` somehow.

- [ ] Find out how to detect coverage change,
- [ ] Implement a check in GH actions,

**Acceptance Criteria**

- [ ] coverage checks on coverage drop, i.e. added a conditional branch that is not reached during the tests,
- [ ] coverage checks pass if coverage stays the same (e.g. editing a markdown file)

**Other information and links**

Seems it may be what we are looking for: https://docs.codecov.com/docs/commit-status

**Comment by q9f** [comment]
This is fully implemented:

https://github.com/ChainSafe/forest/blob/main/.github/workflows/rust.yml#L51-L81

We just need someone with admin access to link our repository to codecov.

https://app.codecov.io/gh/ChainSafe/forest

**Comment by LesnyRumcajs** [comment]
Which part of this exactly fails the job if coverage drops? Looks like it just generates the report and uploads it, or am I missing something?

**Comment by q9f** [comment]
Codecov adds a check to the PR that goes red if coverage drops. It just needs to be linked to our repository. Maybe @noot can activate it.

**Comment by LesnyRumcajs** [comment]
Could you please point me to the documentation on this? I don't really see where it would be failing the CI with the current settings. Right now it wouldn't even fail on upload error (`fail_ci_on_error` defaults to false in [here](https://github.com/codecov/codecov-action#arguments)). If the coverage check would be working it would fail some of the [the past PRs](https://app.codecov.io/gh/ChainSafe/forest/pulls?page=1&state=open&order=-pullid), no?

**Comment by q9f** [comment]
I don't think it's related to the workflow config but I created #1466 to be sure.

I use codecov on other repositories without any github workflow configuration.

**Comment by q9f** [comment]
There is no codecov comment / workflow visible on the repository. It must be a misconfiguration, so we would need someone with admin privileges to fix this.

**Comment by q9f** [comment]
This is how it should look like: https://github.com/q9f/eth.rb/pull/52#issuecomment-1016217010

![Screenshot at 2022-03-07 14-37-15](https://user-images.githubusercontent.com/58883403/157044775-7386ddbd-f1ca-4435-ae55-e5a22226350f.png)

**Comment by LesnyRumcajs** [comment]
Not sure if @noot managed to do that or my attempts succeeded (basically tried to add codecov app to Forest via Chainsafe org) but seems it's working now - see here: https://github.com/ChainSafe/forest/pull/1467
