### ISSUE TITLE
Nightly check: download and use latest snapshot

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1476]
**Issue summary**
Currently, the nightly check uses a fixed snapshot from February due to Forest limitation (it doesn't work yet for NV15). When this limitation is lifted, it should use the last snapshot.

**Task summary**
Download and use the last snapshot in the nightly check.

- [ ] Add a cronjob to download the latest snapshot. Ensure that previous snapshots are deleted to not run out of disk space. 
- [ ] Modify the nightly check to use the latest snapshot. (may not be needed, it already takes the last modified `.car` file from `$HOME/nightly_check/snapshots`. 

**Acceptance Criteria**
- [ ] Nightly check is using the latest snapshot without issues.

**Comment by lemmih** [comment]
This appears to be done (modulo from the dont-run-out-of-space part, it has been moved to a separate issue).
