### ISSUE TITLE
Coverage for binary tests

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1489]
**Issue summary**

Coverage reports are missing runs where the `forest` binary is executed directly, e.g. [cli tests](https://github.com/ChainSafe/forest/blob/main/forest/tests/config_tests.rs). Some attempts were made with adding `--follow-exec` to `tarpaulin` (perhaps the executed binary was not the instrumented one) or creating explicitly an instrumented binary (which was severely timing out, >20mins). 

**Task summary**

- [ ] Investigate how we can make binary tests with coverage check (most likely it should be one binary for most cases, except where some fancy features are used)
- [ ] Implement the change

**Acceptance Criteria**

- [ ] `main` is at least partially [covered](https://app.codecov.io/gh/ChainSafe/forest/blob/main/forest/src/main.rs)
- [ ] coverage step does not take significantly more time than before

**Other information and links**

https://github.com/assert-rs/assert_cmd/issues/57
https://docs.rs/escargot/latest/escargot/
https://github.com/xd009642/tarpaulin/issues/105

An attempt at building instrumented binary once for all tests
```rust
lazy_static!(
    static ref FOREST_BINARY: CargoRun = {
    escargot::CargoBuild::new()
        .bin("forest")
        .current_release()
        .current_target()
        .run()
        .unwrap()
    };
);

// then use with: let cmd = Command::new(FOREST_BINARY.path())

```

**Comment by lemmih** [comment]
This might be solvable once #1558 lands.

**Comment by lemmih** [comment]
`cargo llvm-cov` magically does the right thing. We have good coverage and it doesn't significantly impact testing time.
