### ISSUE TITLE
Hide progress bars behind a config flag

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1508]
**Issue summary**

Right now running Forest in CLI provides a lot of progress bars to track how fast/slow things are going. This is great unless you don't monitor the standard output but browse the logs on a server in case of a failure (which in general should be the main use case once Forest goes full prod). Then your log file becomes bloated.

**Task summary**

- [x] put the existing CLI progress bars behind a configuration option.
- [x] default to show the progress bars to not break the current behaviour (later we can decide on changing this)

**Acceptance Criteria**

- [x] Forest user has the ability to run it without progress bars

**Other information and links**

Sample from logs:
```
 2022-03-29T09:35:36.194Z INFO  chain_sync::chain_muxer                > Local node is behind the network, starting BOOTSTRAP from LOCAL_HEAD = 1534080 -> NETWORK_HEAD = 1674671
^MDownloading headers 0 / 140591 [--------------------------------] 0.00 % 0.00/s ^MDownloading headers 101 / 140591 [>-----------------------] 0.07 % 103.27/s 23m ^MDownloading headers 2538 / 140591 [>----------------------] 1.81 % 1717.13/s 1m ^MDownloading headers 4920 / 140591 [>---------------------] 3.50 % 2487.04/s 55s ^MDownloading headers 7237 / 140591 [=>--------------------] 5.15 % 2919.89/s 46s ^MDownloading headers 9831 / 140591 [=>--------------------] 6.99 % 3300.39/s 40s ^MDownloading headers 12663 / 140591 [=>-------------------] 9.01 % 3639.97/s 35s ^MDownloading headers 15494 / 140591 [==>-----------------] 11.02 % 3893.89/s 32s ^MDownloading headers 18387 / 140591 [==>-----------------] 13.08 % 4104.90/s 30s ^MDownloading headers 21345 / 140591 [===>----------------] 15.18 % 4286.60/s 28s ^MDownloading headers 24124 / 140591 [===>----------------] 17.16 % 4402.39/s 26s ^MDownloading headers 26556 / 140591 [===>----------------] 18.89 % 4440.60/s 26s ^MDownloading headers 27822 / 140591 [===>----------------] 19.79 % 4293.01/s 26s ^MDownloading headers 29144 / 140591 [====>---------------] 20.73 % 4174.78/s 27s ^MDownloading headers 30408 / 140591 [====>---------------] 21.63 % 4064.60/s 27s ^MDownloading headers 32818 / 140591 [====>---------------] 23.34 % 4111.88/s 26s ^MDownloading headers 35611 / 140591 [=====>--------------] 25.33 % 4198.69/s 25s ^MDownloading headers 38494 / 140591 [=====>--------------] 27.38 % 4285.89/s 24s ^MDownloading headers 41433 / 140591 [=====>--------------] 29.47 % 4369.69/s 23s ^MDownloading headers 44416 / 140591 [======>-------------] 31.59 % 4449.55/s 22s ^MDownloading headers 47329 / 140591 [======>-------------] 33.66 % 4515.19/s 21s ^MDownloading headers 50185 / 140591 [=======>------------] 35.70 % 4569.65/s 20s ^MDownloading headers 53075 / 140591 [=======>------------] 37.75 % 4622.27/s 19s ^MDownloading headers 55975 / 140591 [=======>------------] 39.81 % 4671.33/s 18s ^MDownloading headers 58813 / 140591 [========>-----------] 41.83 % 4711.48/s 17s ^MDownloading headers 61764 / 140591 [========>-----------] 43.93 % 4757.18/s 17s ^MDownloading headers 64661 / 140591 [=========>----------] 45.99 % 4795.53/s 16s ^MDownloading headers 67624 / 140591 [=========>----------] 48.10 % 4835.93/s 15s ^MDownloading headers 70572 / 140591 [==========>---------] 50.20 % 4872.49/s 14s ^MDownloading headers 73432 / 140591 [==========>---------] 52.23 % 4900.70/s 14s ^MDownloading headers 76309 / 140591 [==========>---------] 54.28 % 4928.20/s 13s ^MDownloading headers 79271 / 140591 [===========>--------] 56.38 % 4959.30/s 12s ^MDownloading headers 82007 / 140591 [===========>--------] 58.33 % 4974.78/s 12s ^MDownloading headers 84927 / 140591 [============>-------] 60.41 % 5000.19/s 11s ^MDownloading headers 87814 / 140591 [============>-------] 62.46 % 5022.25/s 11s ^MDownloading headers 90636 / 140591 [============>-------] 64.47 % 5039.50/s 10s ^MDownloading headers 93511 / 140591 [=============>-------] 66.51 % 5058.67/s 9s ^MDownloading headers 96313 / 140591 [==============>------] 68.51 % 5073.00/s 9s ^MDownloading headers 99030 / 140591 [==============>------] 70.44 % 5082.24/s 8s ^MDownloading headers 101967 / 140591 [==============>-----] 72.53 % 5102.00/s 8s ^MDownloading headers 104912 / 140591 [==============>-----] 74.62 % 5121.19/s 7s ^MDownloading headers 107920 / 140591 [===============>----] 76.76 % 5142.50/s 6s ^MDownloading headers 110949 / 140591 [===============>----] 78.92 % 5163.76/s 6s ^MDownloading headers 113887 / 140591 [================>---] 81.01 % 5179.92/s 5s ^MDownloading headers 116756 / 140591 [================>---] 83.05 % 5192.32/s 5s ^MDownloading headers 119709 / 140591 [=================>--] 85.15 % 5207.83/s 4s ^MDownloading headers 122627 / 140591 [=================>--] 87.22 % 5221.16/s 3s ^MDownloading headers 125476 / 140591 [=================>--] 89.25 % 5231.08/s 3s ^MDownloading headers 132233 / 140591 [==================>-] 94.06 % 5400.19/s 2s ^MDownloading headers 139336 / 140591 [====================] 99.11 % 5576.38/s 0s ^MDownloading headers 140591 / 140591 [======================] 100.00 % 5607.14/s ^MDownloading headers 140591 / 140591 [======================] 100.00 % 5607.13/s  2022-03-29T09:36:10.073Z INFO  chain_sync::tipset_syncer              > Validating tipset: EPOCH = 1534080, KEY = [Cid(bafy2bzacechrollj3avgjr65j2arueah7zuc7n7xyhkj2z7bevknhy4ygm3oi), Cid(bafy2bzacedvmjetvpzsegdd6bjbfj662iut3lkb7mqorcca7tten24x2jwnka), Cid(bafy2bzacebg6zmgjmpxuko5vy6qdpygdibmtjkfeu5y6ja2gsqqfva36n4o72), Cid(bafy2bzacecligkmb73krut54qvy4ivkomo2dptatxacoeu3nrof5qncsvsfcq), Cid(bafy2bzaceda5dvz7lrtzu32frd7klhhlrmbswmca2xfrsfr6szt35n2jdql6m)]
 2022-03-29T09:36:10.165Z INFO  chain_sync::tipset_syncer              > Validating tipset: EPOCH = 1534081, KEY = [Cid(bafy2bzaceb5ivszui5lhwed7pcy5um4vjoiigqvlsjakedoitwxseh57cenoq), Cid(bafy2bzacec4cy33vqukvnme2j5ff2wpbh3pbrfve54lmw7s5inhwroj4zlgh6), Cid(bafy2bzacebwklwgjndpervlgd4tpzngdavrof6rscaki2liw7ngor4ped427o), Cid(bafy2bzaceb7y3gvdw6ikctwounyva5gvw2ck7yu53cpvwk2idlkv76s5wy7sy), Cid(bafy2bzacebngbv66hzerwlwf5rwi5twmth2wnjqznhoatssy2nclkq2xdpfrq), Cid(bafy2bzacedy5bcxnavua53cejsatlud65y5kncvasxfrjxj4b6kcogoh5tfvo)]
```

**Comment by lemmih** [comment]
Addition: Progress bars should be omitted (or printed differently) by default if stdout is not a tty.
