### ISSUE TITLE
Update Prometheus crate

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1515]
**Issue summary**

Update Prometheus package, for some reason updating it from `0.12` to `0.13` breaks the metrics endpoint. See https://github.com/ChainSafe/forest/issues/1513

**Task summary**

- [ ] Investigate the root cause and upgrade the crate to 0.13 (or higher). Implement necessary changes.

**Acceptance Criteria**

- [ ] Prometheus crate is updated
- [ ] Metrics endpoint works as expected

**Other information and links**

**Comment by LesnyRumcajs** [comment]
It was updated in the meantime to `0.13`
