### ISSUE TITLE
Nightly check: use Forest docker image

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1601]
**Issue summary**

Given after CI is passed we should be confident of the build itself, we can skip it in the nightly check and try to sync with a docker image / docker-compose setup. This way we also ensure that local worker cache/settings/changes are not distorting the results.

**Task summary**

- [ ] Modify nightly check scripts to use docker image (`latest` tag will suffice)
- [ ] Install them on the nightly check machine

**Acceptance Criteria**

- [ ] Forest is using the docker image in the nightly check and not building the binary
- [ ] GH has some downtime from time to time, so it would be good to try a few times to `pull` the image (without some periods of sleep) before reporting an error.

**Other information and links**
