### ISSUE TITLE
Implement proper tagging strategy for docker images

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1602]
**Issue summary**

Right now we only tag whatever gets merged into `main` with `latest`. We should have more fine-grained control over this. To start with, releases should have their own tags. This should be probably implemented [here](https://github.com/ChainSafe/forest/blob/main/.github/workflows/release.yml). Next, the regular merges should get an additional tag - commit digest should be fine, or a combination of day and digest to make it more readable, e.g. `forest:210629_26c85e8`. The current version plus a number of builds since the last bump is also something I've seen in the past e.g. `v0.2.2-42`. Something to discuss.

The `latest` tag should then point to the most recent release tag.

**Task summary**

- [ ] Implement proper release tagging for docker images
- [ ] Implement proper merge commit tagging for docker images

**Acceptance Criteria**

- [ ] tags are properly added/updated on release job
- [ ] tags are properly added/updated on merge commit

**Other information and links**
