### ISSUE TITLE
Utility tool to manage crate versions in Forest

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1612]
**Issue summary**

For now, there's no "inheritance" in cargo projects, that is to say in each crate we have to specify versions separately.

For example, we have currently 26 occurrences of `fvm_shared` dependency in all of the `Cargo.toml` files, each would need to be updated separately on a version bump.

The idea here is to make a tool, a separate binary that would go through the dependencies and perform some actions on them, some ideas:
* align versions,
* bump versions,
* report mismatches

Input to the tool should be in form of either command-line arguments or a config file.

Bonus points: make the tool as Forest independent as possible, with no logic or comments tightly coupled with the Forest codebase. Perhaps after some polishing, it could be published for the entire Rust ecosystem and then folks could e.g. `cargo version-align bump --crate fvm_shared 0.7.1` or `cargo version-align bump --newest fvm_shared`. 

**Task summary**

- [ ] come up with a fancy name for the tool or just `version-align`
- [ ] implement a minimal subset of features to make the tool useful - we'll iterate later. For now, bumping a chosen dependency version to a fixed one should be fine.

**Acceptance Criteria**

- [ ] the tool is included in the CI (with clippy and others),
- [ ] the tool is properly tested via unit & crate tests

**Other information and links**
