### ISSUE TITLE
Skyr (nv16) tracking issue

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1614]
**Issue summary**

- [x] Set upgrade heights for mainnet and calibnet.
- [x] ~Migrate from ohsnap to skyr.~ This can wait.
- [x] Correctly handle v8 actors.
- [x] Sync to calibnet
- [x] Sync to mainnet (after July 6th)

**Other information and links**
