### ISSUE TITLE
Support the butterfly testing network

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1670]
**Issue summary**

It appears that the butterfly network is here to stay and will be used to test new features even before they hit calibnet. We should add support for syncing to the butterfly network.

**Task summary**

- [x] Find the bootstrap peers
- [x] Find the version schedule
- [x] Find the default policy schedule

**Acceptance Criteria**

- [x] sync to butterflynet from a snapshot
- [x] generate butterflynet snapshots

**Other information and links**

The required information might only exist in the source code of Lotus.

**Comment by lemmih** [comment]
Oh, this is a dupe of #1440

**Comment by elmattic** [comment]
We will probably not join butterflynet since it's (again) a private "dev-network" for lotus-only nodes.

Joining Interop network will make more sense for us. As its name stands it's used for cross implementation testing (so a mix of lotus/venus/forest nodes).

**Comment by lemmih** [comment]
I can't seem to find any documentation about the interop network.

**Comment by elmattic** [comment]
> I can't seem to find any documentation about the interop network.

Same for me. I can only find documentation for butterflynet.
https://lotus.filecoin.io/kb/butterfly-network/

**Comment by lemmih** [comment]
Okay, let's close this issue and only support mainnet and calibnet. It does make me a little sad to see butterflynet on https://status.filecoin.io knowing Forest isn't allowed to join but I can learn to live with it. :)

**Comment by lemmih** [comment]
We've been invited into the butterfly network. This will let us test the network upgrade before it goes live on calibnet.

Parameters: https://github.com/filecoin-project/lotus/blob/release/v1.18.0/build/params_butterfly.go
