### ISSUE TITLE
Investigate why we cannot download more than 1 tipset at a time.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1839]
**Issue summary**

In `tipset_syncer.rs`, we have a parameter that defines how many tipsets we request at a time:
https://github.com/ChainSafe/forest/blob/a5cbc53709a962b04fbc8b2be5f4df10f1f6e5fa/blockchain/chain_sync/src/tipset_syncer.rs#L1020-L1021

Increasing this value causes errors while syncing. We need to investigate why this happens and fix it.

**Task summary**

- [ ] Replicate the issue by fetching a calibnet snapshot and attempting to sync with `REQUEST_WINDOW = 10`.
- [ ] Investigate the root cause of the failure and describe it as a comment to this issue.
- [ ] Propose a solution as a comment to this issue.
- [ ] Implement said solution.
- [ ] Test solution on both calibnet and mainnet.

**Acceptance Criteria**

- [ ] Forest can sync correctly with an arbitrary `REQUEST_WINDOW` value, *OR*
- [ ] The reasons why `REQUEST_WINDOW` are compelling and added as a comment in the source code.

**Other information and links**

Filecoin spec: https://spec.filecoin.io/
Lotus: https://github.com/filecoin-project/lotus
Calibnet snapshots: https://cloud.digitalocean.com/spaces/forest-snapshots?i=88c522&path=calibnet%2F

**Comment by lemmih** [comment]
Solution proposed (and tracked by) issue #1911
