### ISSUE TITLE
Add sub-command for downloading mainnet and calibnet snapshots

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1846]
**Issue summary**

Mainnet snapshots are available from FileCoin's S3 bucket and we are hosting our own calibnet snapshots (with mainnet snapshots coming eventually). The forest CLI should have a sub-command for easily downloading the most recent versions of the these snapshots.

**Task summary**

- [x] Add methods for querying our S3 bucket to find the most recent calibnet snapshot.
- [x] Add methods for querying the most recent version of the mainnet snapshot (decide whether to use `curl` or a pure rust approach).
- [x] Add `forest chain fetch` sub-command for downloading/fetching snapshots. It should take an optional `--chain` flag.

**Acceptance Criteria**

- [x] The most recent calibnet snapshot can be downloaded automatically from our S3 bucket.
- [x] The most recent mainnet snapshot can be downloaded automatically from FileCoin's S3 bucket.

**Other information and links**

The mainnet S3 bucket doesn't allow file listings but has a redirect to the most recent snapshot:
```
curl -sI https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car | perl -ne '/x-amz-website-redirect-location:\s(.+)\.car/ && print "$1.sha256sum\n$1.car"' | xargs wget
```

Our calibnet snapshots are here: https://forest-snapshots.fra1.digitaloceanspaces.com/
