### ISSUE TITLE
Define each word in the custom `forest.dic` dictionary

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1854]
**Issue summary**

We are defining a bunch of custom words such `IPFS` and `IPLD`. These words should be defined in a glossary section of the documentation book.

**Tasks**
- [ ] Create `glossary.md` and add it to the markdown documentation book.
- [ ] For each word in `forest.dic`, write a suitable definition and include links to relevant material when possible.
- [ ] Make sure `glossary.md` renders correctly.

**Other information and links**

There's no need to define both `API` and `APIs`. These are two separate words in the dictionary due to limitations of hunspell.
