### ISSUE TITLE
Rubify health check script

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1871]
**Issue summary**

Currently, the [health check script](https://github.com/ChainSafe/forest/blob/main/scripts/sync_check/health_check.sh) is written in bash. For readability and extendability and having a uniform technology in the sync check, it would be great to rewrite it in Ruby. The current script doesn't do any magic, just grabs the metrics and compares a few values there, so it should be straightforward to implement.

It might be an excellent entry task to get exposed to Ruby.

**Task summary**

- [ ] rewrite [health check script](https://github.com/ChainSafe/forest/blob/main/scripts/sync_check/health_check.sh) in Ruby
- [ ] verify that it works the same way as the former bash script (perhaps some basic unit tests?)
- [ ] use it in sync check CI

**Acceptance Criteria**

- [ ] bash script is no longer used in sync check
- [ ] new version has at least the same functionality as the former one

**Other information and links**

https://github.com/ChainSafe/forest/pull/1867

**Comment by LesnyRumcajs** [comment]
Bash is good, and the sync check is rock solid.
