### ISSUE TITLE
Investigate support for ParityDb

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2002]
**Issue summary**
Investigate supporting `ParityDb` from Parity Technologies. `ParityDb` is a blockchain first, ssd optimized kv store, 100% written in Rust. It's actively developed and seems to be usable in production.

The embedded database is known to be a limiting/enabling factor of performances in blockchain clients.
We would like to see if this alternate option to `RocksDB` could work in the context of Forest.

**Task summary**
- [x] figure out how to select this new backend (via a feature flag or at runtime),
- [x] create a `ParityDb` type and implement `Store` interface,
- [x] implement similar unit tests than `RocksDB` but for `ParityDb`,
- [x] evaluate performance and memory impact,
- [x] evaluate overall node stability.
  
**Acceptance Criteria**

Forest should continue to work normally:
- [x] importing a snapshot works.
- [x] syncing up to `HEAD` works.
- [x] exporting a snapshot works.
- [x] rpc service works.
- [x] performance metrics are acceptable (ideally we want something at least as fast/ memory efficient than `RocksDB`).

**Other information and links**

https://github.com/ChainSafe/forest/tree/main/node/db/tests
https://github.com/paritytech/parity-db
https://dot.polkashots.io
`sled`, a recently removed backend in Forest: https://github.com/ChainSafe/forest/pull/1625

**Comment by elmattic** [comment]
Wondering how `ParityDb` can deal with non-graceful shutdown of the node.

**Comment by LesnyRumcajs** [comment]
@elmattic I believe this default option handles such cases https://github.com/paritytech/parity-db/blob/master/src/options.rs#L28
