### ISSUE TITLE
Implement subcommand for RocksDB SST ingestion

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2045]
**Issue summary**

We want to implement a new `forest-cli` subcommand that let the user create and directly prefill forest DB with `.sst` files, the internal RocksDB file format holding sorted key-value pairs (as well as some metadata such as checksum, etc).

The motivation behind this is twofold. Having a better inited DB is critical for overall read performances during the life of a node.

For instance this is the difference between two calibnet nodes, one inited with `.sst` files, the other with `--import-snapshot`:

```
Read latency by levels (micros)

With SST ingestion:
L0: Count: 1,215,531 Average:  2.4862  StdDev: 34.75
L1: Count: 3,921,384 Average: 27.6765  StdDev: 59.24

With snapshot import:
L0: Count: 1,696,985 Average: 17.4042  StdDev: 144.36
L1: Count: 2,914,905 Average: 13.2817  StdDev: 86.88
L2: Count: 4,747,559 Average: 53.3782  StdDev: 79.60
```

With ingestion, read latency is generaly better and DB contains less levels. We are also interested by the reduction of the DB size.

The second reason is that we might want to have for our CI pipelines a faster way to spin up a node, and one way to do it would be by storing the `.sst` files in our Digital Ocean spaces.

A last reason but not mandatory one would be to have a faster alternative than importing a `.car` snapshot. At least we are aiming to be in the same performance ballpark.

EDIT:
From the video in the links, it's said that is is our responsability to provide `.sst` files that are sorted and without overlapping key ranges to avoid the manual call for compaction.

**Task summary**
- [ ] Look for a crate to perform the external sorting,
- [ ] Implement this new `forest-cli` subcommand,
- [ ] Find the right settings so that every `.sst` files are stored in the bottom-most level,
- [ ] Find out a proper size for `.sst` files (512MB or 1GB is a good start),
- [ ] Find out how to benchmark the DBs using `db_bench` tool, create benchmark scripts,
- [ ] Measure performance (read latency, sync time) over a full sync on `calibnet` and `mainnet`.

**Acceptance Criteria**
- [ ] Reading latency is a win over existing state,
- [ ] Full sync time is a win over existing state.

**Other information and links**

https://crates.io/search?q=external%20sort
https://rocksdb.org/blog/2017/02/17/bulkoad-ingest-sst-file.html
https://github.com/EighteenZi/rocksdb_wiki/blob/master/Creating-and-Ingesting-SST-files.md
https://github.com/EighteenZi/rocksdb_wiki/blob/master/Benchmarking-tools.md
https://www.youtube.com/watch?v=sEZxUJMGI9Y&t=1631s

**Comment by lemmih** [comment]
Closing as we're moving to ParityDB.
