### ISSUE TITLE
Investigate in RocksDB Hybrid Compression

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2069]
**Issue summary**
We have deviated in #1481 from `snappy` to `lz4` (probably because `lz4` would lead to a faster snapshot import).

It would be interesting now to test an hybrid way of compressing the levels where a stronger compression is used for the bottom-most level.

Rationale behind this is that `Lmax` is where 99% of the data is stored in a fully filled DB.

We should expose this setting in a way it's always possible to opt out and go back to homegeneous level compression.

**Task summary**
- [ ] Establish a baseline for `mainnet` (`calibnet` is not really interesting to test real world performances)
- [ ] Expose this setting in `RocksDbConfig`
- [ ] Try hybrid compression with `L0-Lmax-1` set to `snappy`, `Lmax` set to `zstd`
- [ ] Try hybrid compression with `L0-Lmax-1` set to `none`, `Lmax` set to `zstd`

**Acceptance Criteria**
- [ ] Importing a snapshot is as fast
- [ ] Read latency is overall better
- [ ] CPU usage should be lower
- [ ] DB is acceptably bigger or as large

**Other information and links**
https://www.youtube.com/watch?v=sEZxUJMGI9Y&t=1583s
https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_bottommost_compression_type

**Comment by lemmih** [comment]
Closing as we're moving to ParityDB.
