### ISSUE TITLE
Investigate in improving RocksDB filters

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2077]
**Issue summary**
In case we want to turn on full bloom filters (see PR #1998), there are some interesting settings to try and performance investigations to do.

When bloom filters are read, those are cached on a per `max_open_files` basis (currently set to `1024`).

This is great but we can have way more `.sst` files in the db than what is allowed by this hard limit.

A better way to cache the bloom filters would be to put them in a dedicated cache that we control.

`set_cache_index_and_filter_blocks` set to `true` put them in the block cache but this would result in competition with the uncompressed blocks.

Partitioned filters should alleviate this problem.

Also to maximize cache usage we should try Ribbon filters, they use less storage bits per key and offer similar false positive (FP) rate than the bloom filters.

**Task summary**

- [ ] Implement cached partitioned filters
- [ ] Implement Ribbon filters
- [ ] Find appropriate values for cache and bits per key
- [ ] Benchmark on a mainnet db
- [ ] Analyse rocksdb stats (hit rate, latency, etc)

**Acceptance Criteria**
- [ ] Importing a snapshot is as fast if not faster
- [ ] Read latency is overall better
- [ ] CPU usage should stay acceptable 
- [ ] DB should be less big

**Other information and links**

http://rocksdb.org/blog/2017/05/12/partitioned-index-filter.html
http://rocksdb.org/blog/2021/12/29/ribbon-filter.html

**Comment by lemmih** [comment]
No longer a priority as ParityDB becomes the default.
