### ISSUE TITLE
Improve snapshot write error handling

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2101]
**Issue summary**

This issue touches both `snapshot export` and `snapshot fetch`. At the moment, both exported and downloaded snapshots are saved immediately to the target location. This is a bit unfortunate because in case of an error or a panic they linger around, potentially causing various problems.

The goal here is to change the logic in both of the commands to write the files to a temporary location and only on a successful passthrough, move them to the target location. In case of an error (except for the checksum fiasco for `snapshot fetch`), the corrupted file should be removed from the temporary directory.

**Task summary**

- [ ] `snapshot export` writes to a temporary location. Only on full success, the snapshot (and the checksum file) are moved to the target directory. Otherwise, the partial file is removed.
- [ ] `snapshot fetch` writes to a temporary location during download. In case of an error during the download, the file should be deleted. In case of an error during checksum verification, the file should not be moved to the target directory but kept in the temporary directory (and the path to it should be displayed to the user).

**Acceptance Criteria**

- [ ] in case of in-flight errors, interrupts etc. the partial snapshots are not pushed to the target directory and are saved to a temporary directory which should not survive OS reboot,
- [ ] in case of a checksum verification fiasco, the faulty snapshot stays in the temporary directory for potential investigation. An informative message is displayed.

**Other information and links**

Feel free to introduce any flags that would make sense and make the API more ergonomic.
