### ISSUE TITLE
Support the new Protocol Labs snapshot service

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2163]
**Issue summary**
We shoud update our forest-cli's `snapshot fetch` subcommand to support the new PL snapshot service: snapshots.mainnet.filops.net.

The old service (fil-chain-snapshots-fallback.s3.amazonaws.com) that we are using today is going to be deprecated at EOY.

**Task summary**
- [ ] Add support for this new service (download + validation)
- [ ] Update other subcommands if needed (ie, `prune`)

**Acceptance Criteria**
- [ ] We can fetch a new snapshot from this new service and sync from it
- [ ] Other related snapshot subcommands still work (`clean`, `list`, `prune`, `remove`)

**Other information and links**
https://pl-strflt.notion.site/pl-strflt/Lightweight-Filecoin-Chain-Snapshots-17e4c386f35c44548f5863afb7b5e024

The new naming scheme is `<height>_YYYY_MM_DDTHH_MM_SSZ.car`.
