### ISSUE TITLE
Add test to validate_chain function

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2181]
**Issue summary**
We would like to add test coverage to the [validate_chain](https://github.com/ChainSafe/forest/blob/main/blockchain/state_manager/src/lib.rs#L1291) function.

This function is very important because it's our main way to produce usable state-diffs when they are occurring.

**Task summary**
- [ ] Find a way to test this function (up to you to decide how, unit or integration test)
- [ ] Make sure warnings can help troubleshooting this kind of unexpected situation (enabling warnings wasn't much help)

**Acceptance Criteria**
- [ ] Regressions like in PR2180 are detected

**Other information and links**
https://github.com/ChainSafe/forest/pull/2180

**Comment by lemmih** [comment]
Done!
