### ISSUE TITLE
Update `serde_ipld_dagcbor` to `0.2.*`

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2215]
**Issue summary**

Currently, Forest is sitting on version `0.1.*` of https://github.com/ipld/serde_ipld_dagcbor. It would be nice to update it to match the dependency from `fvm`. A simple version bump is not enough; there were some changes in the API.

**Task summary**

- [ ] update to `0.2` https://github.com/ChainSafe/forest/blob/62e9509efa1329655a1380bd3bfb1bd787161ced/Cargo.toml#L137
- [ ] resolve API changes

**Acceptance Criteria**

- [ ] all tests are green, and Forest can sync to mainnet and calibnet

**Other information and links**

**Comment by lemmih** [comment]
Dup of #2022. But I like your checkpoints. :)

**Comment by LesnyRumcajs** [comment]
Ah, my bad; I had too high expectations for the GH search.
