### ISSUE TITLE
Tracking issue for `cargo audit` warnings

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2252]
**Issue summary**

- [x] ansi_term is Unmaintained: https://rustsec.org/advisories/RUSTSEC-2021-0139
- [x] difference is unmaintained: https://rustsec.org/advisories/RUSTSEC-2020-0095
- [x] mapr is Unmaintained: https://rustsec.org/advisories/RUSTSEC-2022-0053
- [x] memmap is unmaintained: https://rustsec.org/advisories/RUSTSEC-2020-0077
- [x] Crate `parity-wasm` deprecated by the author: https://rustsec.org/advisories/RUSTSEC-2022-0061
- [x] xml-rs is Unmaintained: https://rustsec.org/advisories/RUSTSEC-2022-0048

full log: https://github.com/ChainSafe/forest/actions/runs/3531600538/jobs/5924950212#step:7:1382

**Other information and links**

**Comment by tyshko5** [comment]
`xml-rs` is unmaintained, but it used by `serde-xml-rs` which is used by `rust-s3`, which we are using the most recent stable version. Therefore no way to get rid of it

**Comment by tyshko5** [comment]
`parity-wasm` became archived very recently, it is used by `fvm-wasm-instrument` probably it's reasonable for `fvm` people to fork it as is and release

**Comment by tyshko5** [comment]
`memmap` is unmaintained, but it used by `bellperson` which is used by `filecoin-proofs-api`, so no way to get rid of it

**Comment by tyshko5** [comment]
`mapr`  is unmaintained, but as it is used by `storage-proof-porep`, so probably one could try to replace it with something better maintained

**Comment by tyshko5** [comment]
`difference` is unmaintained and can be replaced without significant hurdle. I'll create an issue for it

**Comment by tyshko5** [comment]
`ansi_term` is unmaintained and the reason for it's existence in the tree is that `structopt` is using a very old version of `clap`

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/issues/2312

**Comment by lemmih** [comment]
Could you open issue with those other crates to let them know that they're depending on unmaintained crates?

**Comment by tyshko5** [comment]
As we moved to the newest version of `clap` `ansi_term` is gone

**Comment by tyshko5** [comment]
`difference` is gone as well

**Comment by tyshko5** [comment]
`storage-proof-porep` is gone as well
