### ISSUE TITLE
Run stable Forest 🌲 node on Digital Ocean 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2272]
**Issue summary**

Run a stable Forest node for extended periods without breaking. We could potentially get help from ChainSafe Devops for this task.  

Refer to discussion of [Forest Roadmap](https://github.com/ChainSafe/forest/discussions/2172)

**Task summary**

- [ ] Create a droplet that meets Forest hardware requirements for mainnet (the one that is used for sync tests should be fine),
- [ ] Implement an easy-to-use Forest stable node deployment. One way is to use a Docker setup. It should automatically update itself ONLY on new tags. If we don't want to use Docker, there should be a proper cron job set up. All in all, there should be a one-click script that will set up everything,
- [ ] Add monitoring via Grafana,
- [ ] Add alerting to Slack via Grafana https://grafana.com/docs/grafana/v9.0/alerting/notifications/ (a new slack channel may be handy for this)
- [ ] Present the node to the team, along with the maintenance schedule (everyone should be involved, not only the author). 1-2 weeks per person should be okay,

**Acceptance Criteria**

- [ ] node is continuously running,
- [ ] node is updated on a new release tag,
- [ ] monitoring is available
- [ ] team gets alerts on Slack in case of failures,
- [ ] maintenance schedule is put in place,

**Comment by LesnyRumcajs** [comment]
@lerajk I updated the description. Please let me know if you think something else should be added here as well.

One thing I am unsure of is whether we should run a calibnet node as well. It should be quite straightforward with minimal changes (and would potentially enforce better design) and it would be kind of our "staging" area. What do you think? @lemmih @lerajk @elmattic

**Comment by lemmih** [comment]
Yeah, I think it would be worth it to run a stable calibnet node as well.
