### ISSUE TITLE
Add support for ParityDb configuration

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2301]
**Issue summary**

ParityDb doesn't have a lot of knobs but there are some that we would like to expose to the user in our config file. Ie:

```
[parity_db]
stats = false
compression = "lz4" # other possible values are "snappy" and "none"
```

**Task summary**
- [ ] Add similar `parity_db` section than above to forest `Config` struct
- [ ] Change `stats` to `false` by default (to avoid any potential overhead)

**Acceptance Criteria**
- [ ] We can enable statistics manually
- [ ] We can dump the default config file with `config dump`, tweak `parity_db` section and load back the .toml
- [ ] Changing compression works

**Other information and links**

https://docs.rs/parity-db/latest/parity_db/struct.Options.html

**Comment by LesnyRumcajs** [comment]
In general, I feel like the database configuration should be in a separate file. Otherwise we will bump into serialisation/deserialisation issues (I think that at the moment, Forest-paritydb won't be able to ingest a TOML config with a rocksdb section)

**Comment by elmattic** [comment]
If we change the default db backend one day, we can handle this special case and invite the user to comment its rocksdb section and dump a new config file.

It's unlikely that users will jump dynamically between backends.

**Comment by LesnyRumcajs** [comment]
Not that unlikely; I met in Lisbon folks that were interested more in DB observability than overall performance if it was reasonable. Say, ParityDb is more performant, but its ecosystem is close to empty. On the other hand, you would have RocksDb, which would be okay and may have additional tooling for some DB inspection. That would be a reason to switch.

On the code side, we would have less random conditional compiling (that is, it would go away from the node config).

Just something to consider. I'm not pushing it.
