### ISSUE TITLE
Wallet handling testing during CI

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2318]
**Issue summary**

At present, we have a workflow job that downloads a calibnet snapshot, sync to HEAD, and then exports a new snapshot. So far, so good. However, we want to extend these checks over time and they'll quickly grow too complex for the work flow and should therefore be moved to a separate script.

Additionally, we want the script to include basic wallet handling. This means importing a wallet that has been pre-loaded with FIL (from the faucet), checking its balance, creating a new address, moving a tiny amount of FIL from the pre-loaded address to the new address, exporting the wallet, and importing it again.

**Task summary**

- [x] Move CI check to separate script.
- [x] Create wallet, load it with FIL from the faucet, and export it. Figure out how to make it available in the CI server. It doesn't need to be kept secret.
- [x] CI steps:
  - [x] Import the pre-loaded wallet.
  - [x] Check that the wallet has sufficient funds.
  - [x] Create a new address.
  - [x] Move a tiny amount of FIL to the new address.
  - [x] Verify that the transfer was recorded in the blockchain.
  - [x] Export the wallet and import it again.

**Acceptance Criteria**

- [x] Calibnet health checks have been moved to separate script.
- [x] CI still passes.
- [x] Basic wallet handling is tested.

**Other information and links**

Calibnet sync check:
https://github.com/ChainSafe/forest/blob/37340139cb8831c572c1e25357ab452c589920d1/.github/workflows/rust.yml#L125-L177
