### ISSUE TITLE
Add memory leak non-regression test

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2381]
**Issue summary**

On macOS we can run the BSD **leaks** command like this:

`$ leaks --atExit --list -- ./target/release/forest --encrypt-keystore false --target-peer-count 50 --import-snapshot ../../Snapshots/2478000_2023_01_02T08_00_00Z.car --halt-after-import`

Output:

```
Process:         forest [39912]
Path:            /Users/USER/*/forest
Load Address:    0x1046b0000
Identifier:      forest
Version:         ???
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [39911]

Date/Time:       2023-01-02 14:45:25.461 +0100
Launch Time:     2023-01-02 14:33:11.144 +0100
OS Version:      macOS 12.6.2 (21G320)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         246.3M
Physical footprint (peak):  2.0G
----

leaks Report Version: 3.0
Process 39912: 1144 nodes malloced for 1079 KB
Process 39912: 0 leaks for 0 total leaked bytes.
```

This command also returns an exit status which come in handy to check if some leak occurred.

**Task summary**
- [ ] Find an equivalent command of `leaks` on Linux
- [ ] Write a Ruby script to abstract platform differences, and check that there are no leaks in various Forest steps (snapshot import, syncing up to HEAD, following chain for a few epochs)
- [ ] Add the script to our CI pipeline
- [ ] Make sure it's ok to run the script on calibnet (this would be preferable because less heavy than mainnet)

**Acceptance Criteria**
- [ ] New memory leaks should be catch by this script

**Other information and links**

https://www.manpagez.com/man/1/leaks/
https://dr-rost.medium.com/detect-memory-leaks-on-macos-4cf257529aa

**Comment by lemmih** [comment]
I don't think Forest has any memory leaks. We've never found a memory leak in the past and I doubt we'll have one in the future. What we _do_ have are space leaks.

Space leaks are things like a cache that contains data that will never be used again. This is quite different than a memory leak where data is unreachable but not de-allocated. The `leaks` program will only tell us about memory leaks and not space leaks.

**Comment by LesnyRumcajs** [comment]
I agree. Since we are using safe Rust, we'd be basically checking if underlying libraries (e.g., C wrappers) are properly implemented. That would be like writing unit tests for the crates we are using.

**Comment by elmattic** [comment]
Agree too. Closing this issue then.
