### ISSUE TITLE
Implement forest-cli daemon stop command.

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2402]
**Issue summary**

Forest is capable of shut-downing itself because it installed a handler that catches `SIGINT` and `SIGTERM` signals.
So if forest is running in the foreground, hitting Ctrl+C will stop the node.

We would like an equivalent of the Shutdown endpoint in common api of Lotus, as an alternative of resorting only on `ctrl+c` or `kill` commands.

**Task summary**

- [x] Expose a `Shutdown` RPC endpoint with admin rights
- [x] Expose some internal signal to gracefully shutdown forest
- [x] Bind `ctrc+c` and RPC inbound message to it

**Acceptance Criteria**

- [x] Calling `forest-cli shutdown` shutdowns the node
- [x] Using signals (ie `ctrl+c`) still works

**Other information and links**

https://lotus.filecoin.io/lotus/manage/lotus-cli/#lotus-daemon-stop
https://github.com/filecoin-project/lotus/blob/master/api/api_common.go#L51

Note that this command will require that the RPC server be running.
