### ISSUE TITLE
Implementation Of Forest-Calibnet Node Deployment 

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest#2422]
**Issue summary**
This is to implement an easy-to-use Forest stable node deployment. One way is to use a Docker setup. It should automatically update itself ONLY on new tags. If we don't want to use Docker, there should be a proper cron job set up. All in all, there should be a one-click script that will set up everything. Plus we have to test how long Forest can go running before it crashes

**Task summary**

- [x] Ensure the node is continuously running either DO or bare metal servers
- [x] It is also important that the node should be updated with a new tag after every release
- [x] Node infrastructure should be implemented with Terraform & Ansible

**Acceptance Criteria**

- [x] Node is always running and should restart if failure exists
- [x] A simple terraform command should initiate and destroy the infrastructure
- [x] Node meets Forest mainnet's hardware requirements
