### ISSUE TITLE
Set Up Observability For Forest Calibnet & Mainnet

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest#2423]
**Issue summary**
There needs to be some visibility for the forest node infrastructure via observability tools and techniques.

**Task summary**

- [x] Add monitoring via Grafana and Prometheus
- [x] Set up alerting procedures to slack
- [x] Manage the logs properly for storage and maintenance 

**Acceptance Criteria**

- [x] Grafana dashboards are live and running
- [x] Node restart when it crashes with updates to slack
- [x] Logs are properly managed for teams usage
