### ISSUE TITLE
Implement forest-cli info command.

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2442]
**Issue summary**

Forest lacks equivalent Lotus command `info` that prints various informations:

```
$ ./lotus info
Network: calibrationnet
StartTime: 2h8m39s (started at 2023-01-17 11:53:20 +0100 CET)
Chain: [sync behind! (1842h49m0s behind)] [basefee 100 pFIL] [epoch 0]
Peers to: [publish messages 47] [publish blocks 47]
Chain health: 0% [unhealthy]

Default address: address not set

Wallet: 0 address
      Total balance: 0
      Market locked: 0
      Market available: 0

Payment Channels: 0 channel

Deals: 0, 0 B

Bandwidth:
      TotalIn  TotalOut  RateIn    RateOut
      968 MB   31 MB     1.4 kB/s  1.3 kB/s
```

We should start with most basic ones, so `Network`, `StartTime`, `Chain`. Possibly `Peers to` and `Chain health`.

**Task summary**

- [ ] Study how `lotus info` is implemented
- [ ] Implement basic output

**Acceptance Criteria**

- [ ] Calling `forest-cli info` shows some basic node information

**Other information and links**

https://lotus.filecoin.io/lotus/manage/lotus-cli/#lotus-info
https://github.com/filecoin-project/lotus/blob/master/api/api_common.go#L54
https://github.com/filecoin-project/lotus/blob/master/cli/info.go#L31
