### ISSUE TITLE
Self-fund calibnet wallet from forest-cli

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2456]
**Issue summary**

To fund a wallet, one needs to manually go to https://faucet.calibration.fildev.network/, enter the correct wallet address and pray for a minute or two that it works fine. Could we make it a better experience?

**Task summary**

- [ ] Figure out how to access the API programmatically. We may need to talk to the owners since there's spam protection in the faucet. If we use something without such protection, we need to implement it ourselves.
- [ ] implement fund wallet command (available only for calibnet)
- [ ] when creating a wallet, there should be an option to auto fund it
- [ ] consider making it blocking by default and unblocking after funds are received

**Acceptance Criteria**

- [ ] The feature is implemented - the edge cases are handled properly, like node still syncing, faucet service unavailable, timeout on receiving funds etc.
- [ ] The feature is documented (the command, the flags and an entry in our regular documentation)
- [ ] The feature has automatic tests (they may be added to the `slow` category though)

**Other information and links**
