### ISSUE TITLE
Implementation Of Lotus Node Deployment 

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest#2462]
**Issue summary**
This is to implement an easy-to-use Lotus stable node deployment. One way is to use a Docker setup. It should automatically update itself ONLY on new tags. If we don't want to use Docker, there should be a proper cron job set up. All in all, there should be a one-click script that will set up everything. Plus we have to test how long Lotus can go running before it crashes

**Task summary**

- [x] Ensure the node is continuously running either DO or bare metal servers
- [x] Node infrastructure should be implemented with Terraform

**Acceptance Criteria**

- [x] Node is always running 
- [x] A simple terraform command should initiate and destroy the infrastructure
- [x] Node meets Lotus mainnet's hardware requirements
