### ISSUE TITLE
Include Forest 🌲 into launchpad curriculum 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2464]
**Issue summary**

Documentation and content work for Forest 🌲 <> Launchpad

**Acceptance Criteria**
- [x] make PR to [dev tools](https://github.com/protocol/launchpad/tree/main/content/en/curriculum/dev-tools)
- [ ] tutorial for Forest to add in [curriculum](https://curriculum.pl-launchpad.io/tutorials/)
- [ ] tutorial under dev tooling in [curriculum](https://curriculum.pl-launchpad.io/curriculum/dev-tools/fleek/)

**Comment by LesnyRumcajs** [comment]
Launchpad is no more.
