### ISSUE TITLE
add `--exit-after-init` option to Forest

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2528]
**Issue summary**

The name of the flag could be improved. :)

The purpose of this flag is not to start Forest services and exit as soon as basic initialisation is completed. This will open some possibilities, amongst others:
* testing initialisation logic via component tests, like creating the keystore,
* getting the JWT token easily.

The exit should happen before the snapshot download. It may make sense to move the snapshot download as far as possible to allow the initialisation of as many objects as possible

**Task summary**

- [x] introduce the `--exit-after-init` flag to the Forest daemon,
- [x] shuffle the code around so that as many initialisations take place as possible
- [x] write a component test where Forest successfully goes through initialisation :warning: make sure that during the tests a temporary data dir is used - we don't want to override the default keystore by running tests.

**Acceptance Criteria**

- [x] The flag is implemented and the tests are passing, including the new ones,
- [x] The flag is appropriately documented, and the changelog is updated,
- [x] By default, the value of the flag is false,

**Other information and links**
