### ISSUE TITLE
forest-cli - deduce network type

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2609]
**Issue summary**

Currently, we need to add `--chain calibnet` to a bunch of `forest-cli` subcommands. This is not required for most, except, e.g., `snapshot fetch`, which does not require a running node.

Instead, we could ask the Forest daemon via RPC what network it runs. Then do tricks like [here](https://github.com/ChainSafe/forest/blob/main/forest/cli/src/subcommand.rs#L8-L10) based on that.

**Task summary**

- [X] Figure out how to get the network type via RPC call. Something may already be available.
- [X] Don't use the explicit flag in subcommands that communicate with the daemon over RPC,
- [X] The `Address` trick above shouldn't require an explicit flag as well.

**Acceptance Criteria**

- [X] `--chain calibnet` is not required for commands that use the RPC daemon endpoint,
- [X] mainnet is also correctly deduced,
- [X] a basic integration test showing that this works as expected (simply removing the `--chain calibnet` from `forest-cli sync wait` in the CI will do).

**Other information and links**
