### ISSUE TITLE
Snapshots compression for import/export/download

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2741]
**Issue summary**

We could speed up things by downloading compressed snapshots. Mainnet compressed snapshots are significantly smaller (70G vs 130G), and it would make a huge difference for bandwidth-constrained users.

**Task summary**

We should handle both importing and exporting compressed snapshots. Compression could be on by default. This **must** be configurable via configuration and/or flags.

- [x] add `zstd` decompression functionality for importing snapshots. A potential crate to use https://crates.io/crates/zstd
- [x] add a configuration option to use compressed snapshots for downloading (both the `forest` and the `forest-cli snapshot fetch`) and importing,
- [x] add `zstd` compression functionality for exporting snapshots.
- [x] update the snapshot service to upload both compressed and uncompressed files.
- [x] #2873
- [x] #2874
- [x] add a configuration option to use compression when exporting, 

**Acceptance Criteria**

- [x] Limit disk space usage. That is to say; it should be possible to write directly to the `zstd` stream and not create a car file, compress it and then delete it.
- [x] Forest can export compressed snapshots,
- [x] Forest can import compressed snapshots,
- [x] Forest can download compressed snapshots,
- [x] `forest-cli` can download compressed snapshots (right now it's downloading uncompressed ones only)

**Other information and links**

**Comment by elmattic** [comment]
I like it.

**Comment by lemmih** [comment]
@hanabi1224 Is this done?

**Comment by hanabi1224** [comment]
@lemmih updated the checkboxes, `modify forest and forest-cli to prefer compressed files` one is not done

**Comment by lemmih** [comment]
Done.
