### ISSUE TITLE
Remove Forest ChainGetName endpoint

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2902]
**Issue summary**

Forest supports the `ChainGetName` endpoint, returning the network name.

However this method exists only in Forest. An official endpoint achieving similar goal exists and is `Filecoin.StateNetworkName`.

**Task summary**

- [ ] Replace calls to `ChainGetName` with calls to the official endpoint
- [ ] Remove Forest specific endpoint

**Acceptance Criteria**

- [ ] Code that moved from `ChainGetName` to `Filecoin.StateNetworkName` should continue to work

**Other information and links**

https://github.com/filecoin-project/lotus/blob/9321e0fd1404a479d4dee2f1e13d5ea5fbe7ef4e/api/api_full.go#L460
