### ISSUE TITLE
Add support for wallet key deletion

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2939]
**Issue summary**

In `forest-cli` we don't have an easy way for deleting an address from a wallet. The only way to do it right now would be to export, then reimport only the keys we would like to keep.

We should have an easy and safe way to perform this basic operation.

**Task summary**

- [ ] Implement `Filecoin.WalletDelete` endpoint
- [ ] Implement `forest-cli wallet delete` subcommand
- [ ] Implement corresponding unit and smoke tests

**Other information and links**

https://lotus.filecoin.io/lotus/manage/lotus-cli/#lotus-wallet-delete
