### ISSUE TITLE
[Tracking] State mismatch debugging.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3111]
- [ ] https://github.com/ChainSafe/forest/issues/3109 - not only related to this, but mainly
- [ ] Create a manual with debugging approaches: 
  - [ ] how to compare stack traces in lotus and forest
  - [ ] how to validate exactly the epoch we need to debug on both lotus and forest
  - [ ] Attaching a debugger to lotus and forest (we already have a little info on notion: [here](https://www.notion.so/chainsafe/Interop-debugging-v2-57a2bb9aecd74ca89a6b44e460f86d79?pvs=4)
- [ ] Introduce a way to isolate state mismatches (a minimal set of data that could be then used in a unit-test for lotus and forest)

We could begin to gather some of this info by just posting it here or on notion, how do you guys deal with debugging this? It would be very helpful to avoid reinventing the wheel every other week.

**Comment by elmattic** [comment]
Also we can add how to extract a gas trace for a given message with both Lotus and Forest.

**Comment by ruseinov** [comment]
> Also we can add how to extract a gas trace for a given message with both Lotus and Forest.

And I think this should probably be added as a feature to at least Forest. Something that can be enabled easily for debugging purposes. I'd like to move away from having to add debug statements and such for the common use-cases. I think is good to support proper instrumentation.
A good example of how that could be done is present in ParityDB codebase for the `instrumentation` feature.

**Comment by LesnyRumcajs** [comment]
@ruseinov Excellent initiative. I wanted to achieve something like this in the past but didn't manage to find the capacity to finish and publish it. Here are some ideas I collected and tricks I got from the Lotus rockstars. [Link](https://docs.google.com/document/d/1LnVXX9b76TYO4XFFSOHOssneEwMx2-Sf9rLvHeCBv2g/edit?usp=sharing)

**Comment by ruseinov** [comment]
Here's what I use to dump gas traces, thanks for the tips @elmattic . 
[debug_patch_forest.diff.txt](https://github.com/ChainSafe/forest/files/11949736/debug_patch_forest.diff.txt)

**Comment by ruseinov** [comment]
A submodule diff on the lotus side to do the same: 
[ffi-diff.txt](https://github.com/ChainSafe/forest/files/11950538/ffi-diff.txt)

Note, that in order for tracing to be enabled you need to run lotus with `LOTUS_VM_ENABLE_TRACING=1`.
