### ISSUE TITLE
Tracking issue for `forest-cli archive`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3141]
**Issue summary**

In order to generate and maintain the archival data described [here](https://github.com/ChainSafe/forest/blob/main/documentation/src/developer_documentation/filecoin_archive.md), we need better tooling for manipulating archives. This tooling is independent of the daemon (i.e., does not require a running node) and should operate directly on CAR files.

- [x] #3159
- [x] #3204
- [ ] ~`forest-cli archive snapshot --epoch=X --spine`~
- [ ] ~`forest-cli archive snapshot --epoch=X --diff=Y --spine`~
- [ ] ~`forest-cli archive union`~
- [x] #3166

**Other information and links**

**Comment by ruseinov** [comment]
Let's flesh out `forest-cli archive snapshot --epoch=X`.

I'll outline the process the way I understand it
1. We have a car file
2. We index a car file using a car-backed Blockstore
3. We then export a snapshot up to a certain tipset at `--epoch=X`
4. How big of a readable window the snapshot has to represent. e.g. if we export at `--epoch=X`, should `--epoch=x-900` still be verifiable (with all the lookups and such)
5. If exported epoch is not present in the storage - bail.

**Comment by lemmih** [comment]
@ruseinov I created a separate issue for the task: https://github.com/ChainSafe/forest/issues/3159

**Comment by ruseinov** [comment]
> @ruseinov I created a separate issue for the task: #3159

Perfect!
