### ISSUE TITLE
Tracking issue: Forest executable re-organization

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3172]
**Issue summary**

It's becoming increasingly painful to keep all commands in `forest-cli`. Pain points include commands that aren't just RPC calls to the forest-daemon and wallet commands that demand much higher scrutiny — a deeper discussion [happened here](https://github.com/ChainSafe/forest/discussions/2274).

Let's split `forest-cli` into three parts:
 - `forest-cli`: This executable is a human-friendly wrapper around the Forest RPC.
 - `forest-tool`: This executable handles tasks not involving the forest-daemon (such as downloading snapshots).
 - `forest-wallet`: This executable is a human-friendly wrapper around the Forest RPC. It's kept separate from `forest-cli` because it deals with sensitive data and the attack surface should be kept small. This will be the only executable that may access the store of private keys.

Notes:
 - Moving the wallet handling out of the daemon will break compatibility with Lotus. However, we can add a separate compatibility layer between the Lotus-miner and the Forest-daemon. This won't be a concern for quite a while, though.

Sub-tasks:

- [ ] Move non-rpc commands to `forest-tool`
  - [x] `forest-tool fetch-params`
  - [ ] ~~`forest-tool config dump`~~
  - [x] `forest-tool snapshot fetch`
  - [x] `forest-tool snapshot validate`
  - [x] `forest-tool archive info`
  - [x] `forest-tool db clean`, side-note: Maybe this command should be renamed to `db destroy`.
  - [x] `forest-tool db stats`
  - [x] `forest-tool snapshot fetch`
  - [x] `forest-tool snapshot validate`
  - [x] `forest-tool snapshot compress`
  - [ ] `forest-tool state diff`
  - [x] `forest-tool archive info`
  - [ ] `forest-tool archive export`
  - [ ] `forest-tool archive checkpoints`
  - [x] `forest-tool car concat`
- [ ] Print a helpful error message if old commands are used with `forest-cli`.
- [ ] Remove unused command line flags from `forest-cli`.
- [x] Change the default RPC port from 1234 to 2345. We used 1234 to be compatible with Lotus, but we'll handle compatibility separately.
- [x] Move wallet commands to `forest-wallet`
  - [x] `forest-wallet send`
  - [x] `forest-wallet new`
  - [x] `forest-wallet balance`
  - [x] `forest-wallet default`
  - [x] `forest-wallet export`
  - [x] `forest-wallet has`
  - [x] `forest-wallet import`
  - [x] `forest-wallet list`
  - [x] `forest-wallet set-default`
  - [x] `forest-wallet sign`
  - [x] `forest-wallet verify`

**Other information and links**

https://github.com/ChainSafe/forest/discussions/2274

**Comment by aatifsyed** [comment]
Alternative proposal: a single `forest` binary front for these various commands, and better segregation in the code:

- get rid of the `Config` psuedo global - subcommands request what they need through clap, with defaults provided through a config file

**Comment by LesnyRumcajs** [comment]
The configuration is already a known issue and there were [attempts](https://github.com/ChainSafe/forest/pull/2175) to make it right, unfortunately, it got buried at the bottom of the backlog. 

As for one binary, it was the case for Forest some time ago. We decided to [split](https://github.com/ChainSafe/forest/issues/1901). While splitting further the `forest-cli` is not exactly a must.

Having a separate `forest-wallet` is important from a security point of view. It is a critical piece of code that should be easily auditable, and the more clear the boundaries between `forest-wallet` and `forest` the better. Right now, we're not doing very well on this front. See https://github.com/ChainSafe/forest/issues/1517

**Comment by lemmih** [comment]
Done.
