### ISSUE TITLE
Forest CAR roadmap

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3222]
- [x] Uncompressed CARs can be used as a blockstore. https://github.com/ChainSafe/forest/pull/3085
  Forest scans a CAR file, building an index. It then scrolls to file offsets to read IPLD data.
- [x] Manyframe compressed CARs can be used as a blockstore. https://github.com/ChainSafe/forest/pull/3149
  Forest can produce manyframe-compressed CAR files with `forest snapshot compress`. They are backwards compatible with lotus.
  Forest scans manyframe-compressed CAR files, building an index. It scrolls to file offsets to read compressed zstd frames. It scrolls to offsets in zstd frames to read IPLD data.
- [x] Custom car format with pre-indexing and compression. https://github.com/ChainSafe/forest/pull/3213
  Forest can produce `.forest-car.car` files with `forest snapshot compress`. They are backwards compatible with lotus.
  Forest loads an index from `.forest.car` files. It scrolls to fille offsets to read compressed zstd frames. It scrolls to offsets in zstd frames to read IPLD data.
- [x] Remove manyframe compressed CAR support (superseded by `forest-car.car` format)
- [x] All applicable cli frontends (can) use custom car format 
- [x] All applicable cli frontends (can) export custom car format
- [x] Multiple CARs can be used as a blockstore
- [x] CAR backed blockstores are multithreaded
  ```rust
  Blockstore::new(||File::open("<name>.forest-car.car"))
  ```
- [x] CAR backed blockstores have intelligent inter-thread zstd frame caching.
  Might not even need this
- [ ] CARv2 support
- [ ] zstd_seekable support unlocks CARv2-compatible compression support

**Comment by lemmih** [comment]
Closed as complete. CARv2 support and zstd_seekable support may be opened as separate issues later on.
