### ISSUE TITLE
[Enhancement] Use Bytes instead of Vec<u8> for Block to avoid copy.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3398]
**Issue summary**

Currently we are using a `Vec<u8>` for `Block`, because it's convenient given the signature of `Blockstore::get`.
However, there's a good performance boost to be found if we switch to `Bytes` instead, thus getting rid of unnecessary
copying of said bytes into a `Vec`.

Code in question: https://github.com/ChainSafe/forest/blob/10896c2c9f03f895e88cf6110d68a8ac38972df8/src/utils/db/car_stream.rs#L52-L55C1

**Task summary**

- [ ]  convert `Vec<u8>` to `Bytes` in `Block`
- [ ]  make sure that the above change plays well with the rest of the codebase
- [ ]  run `cargo forest-tool benchmark car-streaming` benchmark to verify the performance boost with and without `inspect` arg

**Acceptance Criteria**

- [ ] data field in `Block` struct is converted from `Vec<u8>` to `Bytes` to avoid copy
- [ ] performance boost is validated by benchmarking car streaming
**Other information and links**

We need to figure out what we'll do with `Blockstore::get` implementation for car-backed stores as well as the cache that is also using `Vec<u8>`.

**Comment by ruseinov** [comment]
related to #3314

**Comment by jdjaustin** [comment]
Note to discuss with @lemmih when back from PTO, based on this thread: https://chainsafeio.slack.com/archives/C0144LHN732/p1692632131928259

**Comment by ruseinov** [comment]
Yeah, so this is a quick and dirty solution to have an idea: https://github.com/ChainSafe/forest/pull/3366
In order for this to be interesting it would indeed be nice to employ Bytes when dealing with car-backed stores, for example. Currently not doable due to a variety of constraints, including `Blockchain::get` signature.

**Comment by lemmih** [comment]
The code in #3366 does _not_ make graph traversal faster. We must be all on the same page about this. It is called overfitting when you optimize a benchmark in ways that do not make Forest faster. It's easy to do this accidentally, and one must always be mindful of it.

**Comment by lemmih** [comment]
I don't see how to avoid the copy. Closing.
