### ISSUE TITLE
Fast Finality in Filecoin tracking issue. 

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3685]
Investigate https://github.com/filecoin-project/FIPs/discussions/809 and estimate how long that will take to implement. 

Things to do:

- [ ] Investigate the proposal and assess it's viability.
- [ ] Roughly estimate how long it would take to implement.
- [ ] Implement the proposed algorithm
- [ ] Integrate the implementation

**Comment by lemmih** [comment]
Can https://github.com/ChainSafe/forest/issues/4552 replace this issue?

**Comment by ruseinov** [comment]
superseded by https://github.com/ChainSafe/forest/issues/4552
