### ISSUE TITLE
Add tests for `Filecoin.StateCall` in `api compare` and finish implementation

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#3733]
**Issue summary**

PR #3699 supports testing compatibility for the `Filecoin.StateCall` endpoint. Messages from the 20 first tipsets are used in the tests, but that's not enough to cover all the complexity of Lotus equivalent code (see Lotus `callInternal` implementation).

**Task summary**

- [ ] Create a test message to exercise state forks
- [ ] Create a test message with zero gas fee cap
- [ ] Finish implementation

**Acceptance Criteria**

Make sure responses fail first and then make the tests pass.

- [ ] Current tests with a snapshot are still passing
- [ ] New tests are passing

**Other information and links**

https://github.com/filecoin-project/lotus/blob/0b0d7c96df590ab6ac2db3fb975a112a9a220199/chain/stmgr/call.go#L74C1-L267

**Comment by ansermino** [comment]
@lemmih Is this still issue accurate given #4433?

**Comment by lemmih** [comment]
> @lemmih Is this issue still accurate given #4433?

Yeah, still a bit of work to be done.
