### ISSUE TITLE
Potential issue with hamt ser/de.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3823]
**Issue summary**

While working on https://github.com/ChainSafe/forest/pull/3817 I have encountered an issue, which is thoroughly described in https://github.com/ChainSafe/fil-actor-states/pull/228. 
The issue is that, given exactly the same parameters and the actor version, forest fails to deserialize a hamt map fetched from the storage.

Here's the error

```
called `Result::unwrap()` on an `Err` value: Dynamic(Serialization error for Cbor protocol: Msg("Serde error: Only `Ipld::List` can be deserialized to tuple, input was `Bytes([0, 6, 240, 91, 89, 211, 178, 0, 0, 0, 0, 0, 0])`")
```

**Task summary**

- [ ] Figure out why and how this works on Lotus
- [ ] Introduce support for this decoding on Lotus side.

**Acceptance Criteria**

- [ ] forest's output matches lotus' when testing https://github.com/ChainSafe/forest/pull/3817

**Other information and links**

**Comment by ruseinov** [comment]
It was a different ser/de issue related to bigint.
