### ISSUE TITLE
Implement Ethereum method aliases

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#3959]
**Issue summary**

Lotus supports method aliases for its Ethereum JSON-RPC API.

See file https://github.com/filecoin-project/lotus/blob/v1.25.2/api/eth_aliases.go.

We should implement similar support.

**Task summary**

- [x] Implement similar aliasing
- [x] Find a way to test that aliases work too (this could be done in `forest-tool api compare`)

**Acceptance Criteria**

- [x] Tests are passing

**Other information and links**

https://docs.rs/jsonrpsee/0.22.0/jsonrpsee/struct.RpcModule.html#method.register_alias
(dependent on #3943)
