### ISSUE TITLE
Improve `jsonrpsee` `RpcModule` ergonomics

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#4007]
**Issue summary**

This is a follow-up of #3978.

We had to build an `Arc<RPCState>` to create two `jsonrpsee`'s RPC modules in Forest.

However, a `RpcModule` internally creates an `Arc`.
This results in having to use `Arc<Arc<State>>` at many places, but that would not be strictly necessary if we could create an RPC module from an `Arc`.

**Task summary**

- [x] Add the new constructor in `jsonrpsee` crate
- [x] Get the PR approved
- [ ] Remove one `Arc` level from our `Data` type alias

**Other information and links**

https://docs.rs/jsonrpsee-core/0.21.0/src/jsonrpsee_core/server/rpc_module.rs.html#470

**Comment by aatifsyed** [comment]
https://github.com/paritytech/jsonrpsee/pull/1324
