### ISSUE TITLE
RPC provider methods tracking issue (pre-FVM)

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4164]
**Issue summary**

The following RPC methods are necessary to be compatible with the glif.io public RPC provider.

- [ ] Filecoin.ChainGetNode
- [ ] Filecoin.ChainGetPath - Implemented by flaky.
- [ ] Filecoin.ChainNotify - Implemented but hard to test.
- [ ] Filecoin.ChainPutObj
- [ ] Filecoin.Discover
- [ ] Filecoin.GasEstimateGasPremium
- [ ] Filecoin.GasEstimateMessageGas
- [ ] Filecoin.MinerGetBaseInfo - Implemented but flaky.
- [ ] Filecoin.MsigGetVested
- [ ] Filecoin.MsigGetVestingSchedule
- [ ] Filecoin.StateCall - Implemented by flaky.
- [ ] Filecoin.StateDecodeParams - Difficult to implement.
- [ ] Filecoin.StateMarketBalance
- [ ] Filecoin.StateMarketParticipants
- [ ] Filecoin.StateReplay
- [ ] Filecoin.StateSectorGetInfo - Implemented by flaky.
- [ ] Filecoin.StateVerifierStatus
- [ ] Filecoin.Web3ClientVersion

Lotus documentation for the RPC methods: https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md

**Other information and links**

**Comment by LesnyRumcajs** [comment]
Done except for a few methods that don't seem to be used; if we get some feedback that they're actually needed, we'll revisit the subject.
