### ISSUE TITLE
NV23 tracking

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4318]
## Issue summary

Tracking issue for NV23. See official tracker tracker https://github.com/orgs/filecoin-project/projects/113

- [x] List accepted FIPs,
- [x] assess whether we need to change anything in Forest (changes are mostly contained in the builtin-actors and/or FVM), and if so, estimate the effort
- [x] prepare the upgrade skeleton,
- [x] drive the upgrade across networks

**Comment by LesnyRumcajs** [comment]
Accepted FIPs from https://github.com/filecoin-project/FIPs/discussions/1005#discussion-6643797

**FIP0065 - Ignore built-in market locked balance in circulating supply calculation [(FIP)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0065.md)https://github.com/filecoin-project/FIPs/discussions/719**

Changes in the node, but minimal. We might need to propagate the network version to modules that didn't use it.

**FIP0067 - PoRep Security Policy & Replacement Sealing Enforcement [(FIP Draft)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0067.md)https://github.com/filecoin-project/FIPs/discussions/727**

Depending on the consensus on whether the optional part (tracking the `InitialOldSectors`) should be implemented, there might be a minimal state migration to the miner required, but that's about it.

**FIP0079 - Add BLS Aggregate Signatures to FVM [(FIP)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0079.md)https://github.com/filecoin-project/FIPs/discussions/840**

No changes are required, though we may want to re-use the implemented `verify_bls_aggregate`.

**FIP0082 - Add support for aggregated replica update proofs [(FIP)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0082.md)https://github.com/filecoin-project/FIPs/discussions/752**

Nothing to do on our side.

**FIP0084 - Remove Storage Miner Actor Method ProveCommitSectors [(FIP Draft)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0084.md)https://github.com/filecoin-project/FIPs/discussions/899**

Nothing to do on our side, except bundle changes.

**FIP0085: Convert f090 Mining Reserve Actor to Keyless Account Actor [(FIP Draft)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0085.md) https://github.com/filecoin-project/FIPs/discussions/901**

`f090` will need to be migrated from multisig to keyless account. It should be a simple state migration.

**FIP0090: Non-Interactive PoRep [(FIP Draft)](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0090.md) https://github.com/filecoin-project/FIPs/discussions/854**

There will be a new proof type and a field in the `Policy` struct, which would need to get propagated, but apart from that, no major changes.

**Comment by arajasek** [comment]
> https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0091.md is planned to be shipped as well, requiring node changes. See the corresponding Lotus PR that implements this FIP [filecoin-project/lotus#11969](https://github.com/filecoin-project/lotus/pull/11969)

@LesnyRumcajs  Does this have an owner yet, and what's the timeline for needing this implemented in Forest? I'm interested in making the contribution if it's not already assigned, but I'll probably be slower than you folks.

**Comment by LesnyRumcajs** [comment]
@arajasek It was not assigned, and we'd love your contribution, especially given your subject expertise! The timeline is having this implemented before the calibnet upgrade so that Forest can join testing with Lotus on a devnet and butterflynet (and make a release ~1 week before the calibnet upgrade if possible). I added https://github.com/ChainSafe/forest/issues/4366 if you're still interested.

**Comment by LesnyRumcajs** [comment]
Mainnet upgrade in https://github.com/ChainSafe/forest/pull/4589, release and comms made.
