### ISSUE TITLE
Implement object scheme for `EthBlockNumberOrHash`

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#4359]
## Issue summary

Right now, we only support passing a `String` for `EthBlockNumberOrHash` in our Ethereum RPC API calls. We want to add support for the object scheme as specified in EIP-1898.

## Task summary

- [ ] Implement support for the object scheme
- [ ] Implement serialisation/deserialization tests
- [ ] Add to `api compare` subcommand tests that can have a visible impact (e.g., mainly when `requireCanonical` is true)

## Acceptance Criteria

All tests must pass.

## Other information and links

https://eips.ethereum.org/EIPS/eip-1898#specification
