### ISSUE TITLE
RPC methods required by Boost

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4571]
## Issue summary

- [x] `StateCall` https://github.com/ChainSafe/forest/issues/3733
  - [ ] Additional tests https://github.com/ChainSafe/forest/pull/4435
- [x] #4612
- [x] #4613
- [ ] `EthSubscribe` #4707 
  - [ ] https://github.com/ChainSafe/forest/pull/4122

## Other information and links

Lotus documentation: https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md

**Comment by ansermino** [comment]
@lemmih It seems the only remaining items here are being tracked in other epics. Does it make sense to close this?
