### ISSUE TITLE
F3 integration tracking issue for go-f3 sidecar/FFI approach

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4644]
## Issue summary

This is a child work item of #4552 for tracking the go-f3 integration with sidecar/FFI 

- [x] https://github.com/ChainSafe/forest/issues/4694
- [x] https://github.com/ChainSafe/forest/issues/4695
- [x] https://github.com/ChainSafe/forest/issues/4696
- [x] https://github.com/ChainSafe/forest/issues/4698
- [ ] https://github.com/ChainSafe/forest/issues/4699
- [ ] https://github.com/ChainSafe/forest/issues/4697
- [x] https://github.com/ChainSafe/forest/issues/4700

**Comment by hanabi1224** [comment]
@ansermino I've closed tickets that are completed. Both of the remaining issues are blocked, please feel free to move them to a separate epic.

**Comment by ansermino** [comment]
Closing in favour of #4973
