### ISSUE TITLE
Regression testing for RPC methods

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4657]
## Issue summary

Setting up regression tests for bugs in the RPC methods is demanding. It often requires recreating a complicated blockchain state or loading a snapshot file, which can weigh several gigabytes. Most of the data in the snapshot will be unused, though, and if we trim out dead values, the snapshot files may be small enough to be included in the regression tests.

- [ ] Write a `Blockstore` wrapper, which loads a CAR file, keeps track of which keys are accessed, and writes a minimal CAR file when dropped. This new CAR file can then be used in the regression test.
- [ ] Create convenience functions for invoking RPC methods without spinning up a networked node.
- [ ] Add regression test for #4446. This bug is reproducible with a 4GiB snapshot. If the required data can be reduced to a few KiB, it can be included in the repository.

**Comment by LesnyRumcajs** [comment]
If the required data is larger, perhaps we could move it to a submodule or a downloadable artefact. If all regression snapshots would take less than 1 GB it'd be already great.

**Comment by LesnyRumcajs** [comment]
I wonder if we can use some tooling from Lotus for this, see https://github.com/filecoin-project/FIPs/discussions/1036#discussioncomment-10478096.

**Comment by LesnyRumcajs** [comment]
@hanabi1224 do we consider this PR https://github.com/ChainSafe/forest/pull/5034 to close this initiative?

**Comment by hanabi1224** [comment]
> [@hanabi1224](https://github.com/hanabi1224) do we consider this PR [#5034](https://github.com/ChainSafe/forest/pull/5034) to close this initiative?

I think so.

**Comment by hanabi1224** [comment]
I missed this issue and created a duplicated one #5046

**Comment by LesnyRumcajs** [comment]
Ok, let's close this one, then.
