### ISSUE TITLE
Circle CI Improvements

### ISSUE THREAD

**Issue by GregTheGreek** [ChainSafe/forest#467]
**Task summary**

Circle Improvements: 

- [ ] CodeCov coverage to be added
- [ ] Build specific checks
- [ ] Nightly checks
- [ ] Optimizations
- [ ] Move doc builds from github actions to CircleCI

**Comment by austinabell** [comment]
code cov would be nice too if whoever picks this up has the bandwidth and wants to do :)
