### ISSUE TITLE
Deploy Forest RPC Public Endpoint

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4766]
# Summary

Create a public RPC endpoint that uses Forest as the backend.

# Motivation

- Enable further complaint-driven development of our RPC implementation
- Demonstrate the capabilities of Forest
- Provide a public good for the community

# Tasks

- [ ] Deploy a public-facing instance of Forest
- [ ] Establish metrics collection to understand usage of endpoint
- [ ] Document endpoint in the Forest docs
- [ ] Promote endpoint on Slack and community docs

# Risks & Dependencies

- Forest's RPC endpoints are currently incomplete and have not been battle tested. Such a service may require significant maintenance.
- Load balancing, rate limiting, etc. may require additional components. We may want to explore using lotus-gateway, or building something similar 

# Additional Links & Resources
