### ISSUE TITLE
Tracking issue for moving to FVM-4.4

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4882]
# Summary

# Completion Criteria

- [x] Make sure all dependencies have been updated:
  - [x] `frc46_token`: https://github.com/filecoin-project/actors-utils/pull/238
- [ ] Test Forest against older calibnet snapshots to guard against regressions.

# Additional Links & Resources

**Comment by LesnyRumcajs** [comment]
Note that we shouldn't upgrade until we know more regarding the performance regression when bumping to FVM 4.4 (or 2.7 to 2.9).

See FVM tracking issue https://github.com/filecoin-project/ref-fvm/issues/2058

**Comment by LesnyRumcajs** [comment]
We already moved to 4.5.2
