### ISSUE TITLE
Chain sync RPC methods

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#535]
**Task summary**

Sync methods should be exposed from the jsonrpc server.

Methods include:

- [x] SyncCheckBad - checks if a block was marked as bad, and returns reason if so

- [ ] SyncIncomingBlocks (probably blocked rn without websockets) - incoming, not yet synced block headers

- [x] SyncMarkBad (pretty optional) - Mark blocks as bad manually so they won't be synced

- [x] SyncState - Current status of the chain sync (~opinionated return, not very clearly defined)

- [x] SyncSubmitBlock - Submit newly created block to network through node

**Specification reference**

- 

**Other information and links**
