### ISSUE TITLE
Chain sync CLI commands

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#536]
**Task summary**

CLI match of #535 and will depend on it

AC
- [ ] sync-wait RPC method is implemented
- [ ] the below commands can be called from the CLI client

COMMANDS: (from `lotus sync -h` as reference)
- [ ] status: check sync status
- [ ] wait: Wait for sync to be complete
- [ ] mark-bad: Mark the given block as bad, will prevent syncing to a chain that contains it
- [ ] check-bad: check if the given block was marked bad, and for what reason

**Specification reference**

- 

**Other information and links**

**Comment by nannick** [comment]
Some of the commands take a block as a input for the command.  Is there a preference for what that input should look like? Should it be a file with the block's json in it? Or maybe just a string?

**Comment by austinabell** [comment]
> Some of the commands take a block as a input for the command. Is there a preference for what that input should look like? Should it be a file with the block's json in it? Or maybe just a string?

None of these commands take in a block as input and none of the values should be in JSON. I would look to Lotus for their UX, for this it doesn't matter if we match theirs, but a familiar UX would be ideal to allow clients to be interchangeable.

For example in the case of `check-bad` and `mark-bad` the input is just a Cid string (not json formatted) which you can find in their code. Unfortunately their CLI docs with `lotus sync check-bad -h` doesn't indicate these things though, so when possible please provide descriptions for ours.
