### ISSUE TITLE
Connect P2P Layer to Chain/Sync Manager

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#83]
Need to determine the required tasks to connect the P2P layer and the local chain manager. 

- [ ] Implement Chain Manager; see #85 
- [ ] Implement SyncManager; see #34 
- [ ] Implement BlockSync; see #101
- [ ] Implement Bitswap; see #100 
- [ ] Implement blockchain sync process #115

**Comment by dutterbutter** [comment]
Closing this in favor of #223
